name: Green Contributions

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  contribution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "mms1688"
          git config user.email "mms1688@users.noreply.github.com"

      - name: Generate Random Activity
        run: |
          COMMITS=$((RANDOM % 8 + 1))

          for ((i=1;i<=COMMITS;i++))
          do
            echo "$(date) - $RANDOM" >> activity.txt
            git add activity.txt
            git commit -m "Update $i" || true
          done

      - name: Push Changes
        run: |
          git push
